### ISSUE TITLE
Cookies does not work when dot is used in their name.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/CookiesBundle#19]
Example given in documentation does not work due to cookie name `ongr_demo.foo` having a dot.

**Comment by GrandLTU** [comment]
Also when having both `ongr_demo.foo` and `ongr_demo_foo` cookies cookies does not work.

**Comment by ndinh215** [comment]
@saimaz , the root cause of this issue is the difference between a cookie name and cookie model name. Currently, we are getting a cookie to build a cookie model basing on the cookie model name (config file):
```
$cookie = $this->getHttpCookie($cookieModel, $request);
```
-> when they change a cookie with different name, the related cookie model won't work.

Here, we should think how to dynamically build cookie model according to cookie name.

@saimaz , @mvar , @murnieza How do you think?

**Comment by saimaz** [comment]
I think we should not try to invent some workarounds. Let's simply write in the docs very clearly that dots in the name are not allowed. And that's it.

**Comment by ndinh215** [comment]
Closes #19
